# ===================================
# CONFIGURACIÓN DE MACETAS MÁGICAS
# ===================================
# Plugin: SurvivalCore
# Sistema escalable de macetas que aceptan flores mágicas
# ACTUALIZADO v1.1 - Animaciones y restricciones mejoradas
# ===================================

# Configuración general del sistema
settings:
  # Nivel máximo de macetas (1-5)
  max_level: 5

  # Máximo de macetas por jugador (0 = ilimitado)
  max_pots_per_player: 10

  # 🆕 DISTANCIA MÍNIMA ENTRE MACETAS (en bloques)
  min_distance_between_pots: 2

  # 🆕 BLOQUEAR FLORES NORMALES (solo permiten flores mágicas)
  block_normal_flowers: true

  # Habilitar efectos visuales y sonoros
  enable_effects: true

  # 🆕 HABILITAR ANIMACIONES MEJORADAS DE COLOCACIÓN
  enable_enhanced_placement_animations: true

  # Habilitar partículas automáticas
  enable_particles: true

  # Intervalo de aplicación de efectos (en ticks, 60 = 3 segundos)
  effect_interval: 60

  # Intervalo de partículas (en ticks, 20 = 1 segundo)
  particle_interval: 20

  # Habilitar verificación de línea de vista para efectos
  require_line_of_sight: false

# ===================================
# 🆕 CONFIGURACIÓN DE ANIMACIONES
# ===================================

animations:
  # Configuración de la animación de colocación
  placement:
    # Duración de la animación en ticks (40 ticks = 2 segundos)
    duration: 40

    # Radio inicial de la espiral
    initial_radius: 0.8

    # Radio final de la espiral
    final_radius: 0.5

    # Altura máxima de la espiral
    max_height: 1.5

    # Grados por tick de rotación
    rotation_speed: 15

    # Partículas por tick durante la animación
    particles_per_tick: 1

  # Configuración del anillo final para niveles altos
  final_ring:
    # Nivel mínimo para mostrar el anillo
    min_level: 3

    # Radio base del anillo
    base_radius: 1.5

    # Radio adicional por nivel
    radius_per_level: 0.3

    # Número base de puntos en el anillo
    base_points: 12

    # Puntos adicionales por nivel
    points_per_level: 2

# ===================================
# 🆕 CONFIGURACIÓN DE RESTRICCIONES
# ===================================

restrictions:
  # Lista de flores normales bloqueadas (no se pueden usar)
  blocked_flowers:
    - POPPY
    - DANDELION
    - BLUE_ORCHID
    - ALLIUM
    - AZURE_BLUET
    - RED_TULIP
    - ORANGE_TULIP
    - WHITE_TULIP
    - PINK_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - LILY_OF_THE_VALLEY
    - WITHER_ROSE
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
    - SWEET_BERRY_BUSH

  # Verificación de distancia
  distance_check:
    # Habilitar verificación de distancia
    enabled: true

    # Modo de cálculo: "2D" (solo X,Z) o "3D" (X,Y,Z)
    calculation_mode: "3D"

    # Verificar solo en el mismo mundo
    same_world_only: true

# ===================================
# CONFIGURACIÓN POR NIVEL
# ===================================

levels:
  1:
    # Rango de efectos en bloques
    range: 3
    # Multiplicador de efectos (1.0 = normal)
    effect_multiplier: 1.0
    # 🆕 Partículas en animación de colocación
    placement_particles: "VILLAGER_HAPPY"
    # 🆕 Intensidad de efectos especiales
    special_effects_intensity: 1
    # Costo de crafting/upgrade
    craft_cost:
      experience: 10
      materials:
        clay: 4
        bone_meal: 2
        glowstone_dust: 1

  2:
    range: 5
    effect_multiplier: 1.2
    placement_particles: "VILLAGER_HAPPY"
    special_effects_intensity: 1
    craft_cost:
      experience: 25
      materials:
        clay: 8
        bone_meal: 4
        glowstone_dust: 2
        redstone: 2

  3:
    range: 7
    effect_multiplier: 1.4
    placement_particles: "ENCHANTMENT_TABLE"
    special_effects_intensity: 2
    craft_cost:
      experience: 50
      materials:
        clay: 16
        bone_meal: 8
        glowstone_dust: 4
        redstone: 4
        ender_pearl: 1

  4:
    range: 9
    effect_multiplier: 1.6
    placement_particles: "ENCHANTMENT_TABLE"
    special_effects_intensity: 3
    craft_cost:
      experience: 100
      materials:
        clay: 32
        bone_meal: 16
        glowstone_dust: 8
        redstone: 8
        ender_pearl: 2
        diamond: 1

  5:
    range: 11
    effect_multiplier: 2.0
    placement_particles: "ENCHANTMENT_TABLE"
    special_effects_intensity: 4
    craft_cost:
      experience: 200
      materials:
        clay: 64
        bone_meal: 32
        glowstone_dust: 16
        redstone: 16
        ender_pearl: 4
        diamond: 2
        nether_star: 1

# ===================================
# CONFIGURACIÓN DE EFECTOS
# ===================================

effects:
  # Duración base de los efectos de poción (en ticks)
  base_duration: 80

  # Multiplicador de duración por nivel de maceta
  duration_per_level: 1.2

  # Configuración específica por tipo de flor
  flowers:
    love_flower:
      # Tipo de efecto de poción
      effect_type: "REGENERATION"
      # Nivel base del efecto (0-based, 0 = nivel I)
      base_amplifier: 0
      # ¿El nivel del efecto aumenta con el nivel de la maceta?
      scales_with_pot_level: true
      # Duración especial (0 = usar base_duration)
      custom_duration: 0
      # Configuración de partículas
      particles:
        type: "HEART"
        count: 5
        spread: 0.3

    healing_flower:
      effect_type: "INSTANT_HEALTH"
      base_amplifier: 0
      scales_with_pot_level: false
      custom_duration: 1  # Instantáneo
      particles:
        type: "VILLAGER_HAPPY"
        count: 8
        spread: 0.4

    speed_flower:
      effect_type: "SPEED"
      base_amplifier: 0
      scales_with_pot_level: true
      custom_duration: 0
      particles:
        type: "CRIT"
        count: 6
        spread: 0.35

    strength_flower:
      effect_type: "INCREASE_DAMAGE"
      base_amplifier: 0
      scales_with_pot_level: true
      custom_duration: 0
      particles:
        type: "CRIT_MAGIC"
        count: 4
        spread: 0.25

    night_vision_flower:
      effect_type: "NIGHT_VISION"
      base_amplifier: 0
      scales_with_pot_level: false
      custom_duration: 240  # 12 segundos
      particles:
        type: "ENCHANTMENT_TABLE"
        count: 10
        spread: 0.5

# ===================================
# CONFIGURACIÓN DE PARTÍCULAS
# ===================================

particles:
  # Partículas cuando la maceta está vacía
  idle:
    type: "VILLAGER_HAPPY"
    count: 2
    spread: 0.2
    speed: 0.02

  # Partículas de área de efecto (aparecen ocasionalmente)
  area_effect:
    enabled: true
    # Probabilidad de aparecer cada ciclo (0.0-1.0)
    chance: 0.3
    # Número de partículas en el anillo
    ring_particles: 8

  # 🆕 Partículas de colocación mejoradas
  placement:
    count: 20
    spread: 0.4
    speed: 0.1
    # Partículas adicionales para niveles altos
    enhanced_for_high_levels: true

  # 🆕 Partículas de error
  error:
    type: "BLOCK_CRACK"
    material: "REDSTONE_BLOCK"
    count: 10
    spread: 0.3

# ===================================
# CONFIGURACIÓN DE SONIDOS
# ===================================

sounds:
  # 🆕 Sonidos de colocación mejorados
  placement:
    initial:
      sound: "BLOCK_GRASS_PLACE"
      volume: 1.0
      pitch: 1.2

    # Sonido durante la animación (opcional)
    animation:
      enabled: false
      sound: "BLOCK_NOTE_BLOCK_CHIME"
      volume: 0.3
      pitch: 1.5
      interval: 10  # Cada X ticks

    # Sonido final de colocación
    final:
      sound: "BLOCK_ENCHANTMENT_TABLE_USE"
      volume: 0.8
      pitch: 1.5
      delay: 40  # Al final de la animación

  # 🆕 Sonidos de error
  error:
    sound: "BLOCK_NOTE_BLOCK_BASS"
    volume: 1.0
    pitch: 0.8

  # Sonidos al romper la maceta
  breaking:
    sound: "BLOCK_GRASS_BREAK"
    volume: 1.0
    pitch: 0.9

  # Sonidos al plantar una flor
  flower_plant:
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 0.8
    pitch: 1.2

  # Sonidos específicos por flor al plantar
  flower_specific:
    love_flower: "ENTITY_EXPERIENCE_ORB_PICKUP"
    healing_flower: "ENTITY_PLAYER_LEVELUP"
    speed_flower: "ENTITY_HORSE_GALLOP"
    strength_flower: "ENTITY_IRON_GOLEM_ATTACK"
    night_vision_flower: "BLOCK_ENCHANTMENT_TABLE_USE"

# ===================================
# CONFIGURACIÓN DE SEGURIDAD
# ===================================

security:
  # Prevenir duplicación de macetas
  prevent_duplication: true

  # Verificar integridad de metadatos
  verify_metadata: true

  # Registrar todas las acciones en console
  log_actions: true

  # Límite de macetas por chunk (0 = ilimitado)
  max_pots_per_chunk: 16

  # 🆕 Verificaciones adicionales de seguridad
  additional_checks:
    # Verificar que la maceta sigue siendo válida antes de aplicar efectos
    validate_before_effects: true

    # Verificar que el bloque sigue siendo una maceta
    validate_block_type: true

    # Limpiar macetas inválidas automáticamente
    auto_cleanup_invalid: true

  # Mundos donde NO se pueden colocar macetas mágicas
  disabled_worlds:
    - "world_nether_disabled"
    - "world_end_disabled"

  # Requiere permisos específicos para usar
  require_permissions: true

# ===================================
# CONFIGURACIÓN DE PERSISTENCIA
# ===================================

persistence:
  # Guardar datos automáticamente
  auto_save: true

  # Intervalo de guardado automático (en ticks)
  save_interval: 6000  # 5 minutos

  # Archivo donde guardar las macetas activas
  data_file: "magic_flowerpots.yml"

  # Mantener backups de datos
  keep_backups: true

  # Número máximo de backups
  max_backups: 3

# ===================================
# CONFIGURACIÓN DE RENDIMIENTO
# ===================================

performance:
  # Máximo de macetas que pueden estar activas simultáneamente
  max_active_pots: 1000

  # Usar async para procesamiento de efectos
  async_processing: true

  # Batch size para procesamiento
  batch_size: 50

  # Tiempo máximo de procesamiento por tick (en nanosegundos)
  max_processing_time: 2000000  # 2ms

  # 🆕 Optimizaciones para animaciones
  animation_optimizations:
    # Limitar animaciones simultáneas
    max_concurrent_animations: 10

    # Reducir partículas si hay lag
    reduce_particles_on_lag: true

    # TPS mínimo para mostrar animaciones completas
    min_tps_for_full_animations: 18.0

  # Optimizar partículas para mejor rendimiento
  optimize_particles: true

  # Reducir efectos cuando hay muchos jugadores cerca
  reduce_effects_on_crowding: true

  # Límite de jugadores para activar reducción
  crowding_threshold: 5

# ===================================
# MENSAJES PERSONALIZABLES
# ===================================

messages:
  pot_placed: "&a✓ Maceta Mágica colocada correctamente."
  pot_info_level: "&7Nivel: &b%level% &7| Rango: &a%range% bloques"
  pot_has_flower: "&d🌸 Contiene: %flower_name%"
  pot_broken: "&e⚡ Maceta Mágica recogida correctamente."
  flower_returned: "&d🌸 La flor también ha sido devuelta."
  flower_planted: "&a✓ %flower_name% &aplantada correctamente!"
  effect_range_info: "&bLa maceta ahora irradia efectos en %range% bloques de distancia."

  # Errores
  no_permission_place: "&cNo tienes permisos para colocar Macetas Mágicas."
  no_permission_break: "&cNo tienes permisos para romper Macetas Mágicas."
  no_permission_use: "&cNo tienes permisos para usar Macetas Mágicas."
  invalid_location: "&cNo puedes colocar una Maceta Mágica aquí."
  location_requirements: "&7Debe estar en una superficie sólida y tener espacio libre arriba."
  pot_limit_reached: "&cHas alcanzado el límite de Macetas Mágicas que puedes colocar."
  not_magic_flower: "&cEsta no es una flor mágica válida."

  # 🆕 Nuevos mensajes de error
  too_close_to_other_pot: "&cNo puedes colocar una Maceta Mágica tan cerca de otra."
  min_distance_required: "&7Debe estar al menos a %distance% bloques de distancia de otras macetas mágicas."
  normal_flowers_blocked: "&c❌ Esta maceta solo acepta flores mágicas especiales."
  normal_flowers_explanation: "&7Las flores normales no tienen propiedades mágicas."

  # Información
  pot_empty_status: "&7Estado: &eESPERANDO FLOR"
  pot_active_status: "&7Estado: &aACTIVA"
  pot_active_time: "&7Activa desde: %time%"

  # Ayuda actualizada
  info_place_instruction: "&a▶ Coloca en el suelo para usar"
  info_plant_instruction: "&a▶ Click con flor mágica para plantar"
  info_level_benefit: "&e▶ Mayor nivel = mayor rango"
  info_flower_restriction: "&7▶ Solo acepta flores mágicas especiales"
  info_distance_restriction: "&7▶ Mantén distancia entre macetas"
  info_normal_flowers_blocked: "&c▶ Las flores normales no funcionan"

# ===================================
# CONFIGURACIÓN DEBUG
# ===================================

debug:
  # Habilitar logs detallados
  verbose_logging: false

  # Mostrar información de rendimiento
  show_performance_stats: false

  # Intervalo de stats de rendimiento (en ticks)
  performance_stats_interval: 1200  # 1 minuto

  # Guardar logs de debug en archivo
  save_debug_logs: false

  # 🆕 Debug específico para nuevas funcionalidades
  new_features_debug:
    # Logs de verificación de distancia
    log_distance_checks: false

    # Logs de animaciones
    log_animations: false

    # Logs de bloqueo de flores normales
    log_flower_blocks: false