name: SurvivalCore
version: '${project.version}'
main: gc.grivyzom.survivalcore.Main
api-version: '1.20'
authors: [ Brocolitx ]
description: Plugin principal para el servidor de supervivencia con soporte híbrido Bedrock/Java
website: https://grivyzom.gc/

# Dependencias opcionales - ACTUALIZADO
softdepend: [LuckPerms, PlaceholderAPI, Vault]

commands:
  # Comandos básicos existentes
  repair:
    description: Repara el item que tienes en la mano
    usage: /repair
    aliases: [reparar]
  birthday:
    description: Configura tu fecha de cumpleaños
    usage: /birthday [fecha]
  perfil:
    description: Ver el perfil de un jugador
    usage: /perfil [jugador]
  score:
    description: Ver tu puntuación
    usage: /score
  genero:
    description: Configura tu género
    usage: /genero
  lectern:
    description: Comandos del atril mágico
    usage: /lectern
  # Comandos de transferencia XP
  xpgive:
    description: Dar experiencia a un jugador
    usage: /xpgive <jugador> <cantidad>
    permission: survivalcore.xptransfer.give
  xptransfers:
    description: Ver historial de transferencias
    usage: /xptransfers
  xptransferlog:
    description: Ver log de transferencias
    usage: /xptransferlog
    permission: survivalcore.xptransfer.log
  # Comandos SellWand
  sellwand:
    description: Obtener vara de venta
    usage: /sellwand
    aliases: [sw]
    permission: survivalcore.sellwand.use
  # Comandos Cheques XP
  cheque:
    description: Crear cheques de experiencia
    usage: /cheque <cantidad>
    permission: survivalcore.cheque.create
  # ========== COMANDOS DE RANKUP HÍBRIDOS ==========
  rankup:
    description: Comando principal del sistema de rankup híbrido
    usage: |
      /rankup - Intentar hacer rankup
      /rankup info - Ver información de tu rango
      /rankup progress - Ver progreso detallado
      /rankup list - Ver lista de rangos
      /rankup help - Mostrar ayuda
    aliases: [ru]
    permission-message: "§cNo tienes permisos para usar este comando."
  prestige:
    description: Comando del sistema de prestige
    usage: |
      /prestige - Intentar hacer prestige
      /prestige info - Ver información de prestige
      /prestige help - Mostrar ayuda
      /prestige list - Ver lista de prestiges
    aliases: [prestigio, prest]
    permission-message: "§cNo tienes permisos para usar este comando."
  ranks:
    description: Menú híbrido de rangos (detecta automáticamente Bedrock/Java)
    usage: |
      /ranks - Abrir menú automático (Bedrock/Java)
      /ranks gui - Forzar interfaz gráfica
      /ranks list - Ver lista de rangos en chat
      /ranks top - Ver ranking de jugadores
      /ranks client - Ver información de tu cliente
      /ranks debug - Debug del sistema (admin)
      /ranks fix - Reparar sistema de menús (admin)
      /ranks status - Ver estado del sistema
    aliases: [rangos, ranking]
    permission-message: "§cNo tienes permisos para usar este comando."
  xpbank:
    description: Obtener ánforas de experiencia (banco de XP)
    usage: |
      /xpbank - Obtener 1 ánfora vacía
      /xpbank <cantidad> - Obtener cantidad específica de ánforas vacías
      /xpbank <cantidad> <xp> - Obtener ánforas con XP específica
    permission: survivalcore.xpbank.give
    aliases: [anfora, experiencepot]
  # ========== 🆕 COMANDOS DE MACETAS MÁGICAS ==========
  flowerpot:
    description: Gestión de Macetas Mágicas y Flores Mágicas
    usage: |
      === COMANDOS DE MACETAS ===
      /flowerpot give <jugador> [nivel] [cantidad] - Dar macetas mágicas
      /flowerpot info - Ver información de la maceta en tu mano
      /flowerpot stats - Ver estadísticas del sistema (admin)
      /flowerpot reload - Recargar configuración (admin)
      
      === COMANDOS DE FLORES ===
      /flowerpot giveflower <jugador> <tipo> [nivel] [cantidad] - Dar flores mágicas
      /flowerpot list - Ver todas las flores disponibles
      
      === AYUDA ===
      /flowerpot help - Mostrar ayuda completa
      /flowerpot restrictions - Ver restricciones del sistema
    aliases: [maceta, magicpot, mpot, magicflower]
    permission: survivalcore.flowerpot.use
    permission-message: "§cNo tienes permisos para usar este comando."
  # ========== 🆕 COMANDOS DE FLORES MÁGICAS ==========
  magicflower:
    description: Gestión de Flores Mágicas
    usage: |
      /magicflower give <jugador> <tipo> <cantidad> <nivel> - Dar flores mágicas
      /magicflower list - Ver todas las flores mágicas disponibles
      /magicflower info - Ver información de la flor en tu mano
      /magicflower help - Mostrar ayuda
    aliases: [flor, flower, mflower]
    permission: survivalcore.magicflower.use
    permission-message: "§cNo tienes permisos para usar este comando."
  repairanim:
    description: Comandos administrativos del sistema de reparación
    usage: /repairanim <subcomando>
    permission: survivalcore.repair.admin
# Permisos del sistema - ACTUALIZADO
permissions:
  # Permisos básicos existentes
  survivalcore.repair:
    description: Permite usar el comando repair
    default: true

  survivalcore.birthday:
    description: Permite configurar cumpleaños
    default: true

  survivalcore.perfil:
    description: Permite ver perfiles
    default: true

  survivalcore.score:
    description: Permite ver puntuación
    default: true

  survivalcore.genero:
    description: Permite configurar género
    default: true

  # Permisos SellWand
  survivalcore.sellwand.*:
    description: Todos los permisos de SellWand
    default: op
    children:
      survivalcore.sellwand.use: true
      survivalcore.sellwand.admin: true

  survivalcore.sellwand.use:
    description: Permite usar las varas de venta
    default: true

  survivalcore.sellwand.admin:
    description: Permisos administrativos de SellWand
    default: op

  # Permisos XP Transfer
  survivalcore.xptransfer.*:
    description: Todos los permisos de transferencia XP
    default: op
    children:
      survivalcore.xptransfer.give: true
      survivalcore.xptransfer.log: true

  survivalcore.xptransfer.give:
    description: Permite dar XP a otros jugadores
    default: op

  survivalcore.xptransfer.log:
    description: Permite ver logs de transferencias
    default: op

  # Permisos Cheques XP
  survivalcore.cheque.*:
    description: Todos los permisos de cheques
    default: op
    children:
      survivalcore.cheque.create: true
      survivalcore.cheque.admin: true

  survivalcore.cheque.create:
    description: Permite crear cheques de XP
    default: true

  survivalcore.cheque.admin:
    description: Permisos administrativos de cheques
    default: op

  # ========== PERMISOS DE RANKUP HÍBRIDO ==========

  # Permisos básicos de rankup - Todos los jugadores pueden usar
  survivalcore.rankup.progress:
    description: Permite ver progreso de rankup
    default: true

  survivalcore.rankup.list:
    description: Permite ver lista de rangos
    default: true

  survivalcore.rankup.gui:
    description: Permite abrir menús de rangos (Bedrock/Java)
    default: true

  survivalcore.rankup.history:
    description: Permite ver historial de rankups
    default: true

  # 🆕 NUEVOS PERMISOS HÍBRIDOS
  survivalcore.rankup.bedrock:
    description: Permite usar menús optimizados para Bedrock
    default: true

  survivalcore.rankup.java:
    description: Permite usar menús interactivos de Java
    default: true

  survivalcore.rankup.hybrid:
    description: Permite detección automática y menús híbridos
    default: true

  survivalcore.rankup.client.info:
    description: Permite ver información del tipo de cliente
    default: true

  # Permisos de prestige
  survivalcore.prestige:
    description: Permite usar el sistema de prestige
    default: true

  survivalcore.prestige.use:
    description: Permite hacer prestige
    default: true

  survivalcore.prestige.info:
    description: Permite ver información de prestige
    default: true

  # Permisos administrativos de rankup
  survivalcore.rankup.admin:
    description: Permisos administrativos del sistema de rankup
    default: op

  survivalcore.rankup.reload:
    description: Permite recargar la configuración de rankup
    default: op

  survivalcore.rankup.bypass:
    description: Permite saltarse requisitos de rankup
    default: op

  survivalcore.rankup.others:
    description: Permite hacer rankup a otros jugadores
    default: op

  # 🆕 NUEVOS PERMISOS ADMINISTRATIVOS HÍBRIDOS
  survivalcore.rankup.debug.hybrid:
    description: Permite debug del sistema híbrido
    default: op

  survivalcore.rankup.fix:
    description: Permite reparar sistema de menús
    default: op

  survivalcore.rankup.force.client:
    description: Permite forzar tipo de cliente para jugadores
    default: op

  # Permisos consolidados para facilitar gestión
  survivalcore.rankup.*:
    description: Todos los permisos de rankup (jugadores)
    default: true
    children:
      survivalcore.rankup: true
      survivalcore.rankup.use: true
      survivalcore.rankup.info: true
      survivalcore.rankup.progress: true
      survivalcore.rankup.list: true
      survivalcore.rankup.gui: true
      survivalcore.rankup.history: true
      survivalcore.rankup.bedrock: true
      survivalcore.rankup.java: true
      survivalcore.rankup.hybrid: true
      survivalcore.rankup.client.info: true
      survivalcore.prestige: true
      survivalcore.prestige.use: true
      survivalcore.prestige.info: true

  survivalcore.rankup.admin.*:
    description: Todos los permisos administrativos de rankup híbrido
    default: op
    children:
      survivalcore.rankup.*: true
      survivalcore.rankup.admin: true
      survivalcore.rankup.reload: true
      survivalcore.rankup.bypass: true
      survivalcore.rankup.others: true
      survivalcore.rankup.debug.hybrid: true
      survivalcore.rankup.fix: true
      survivalcore.rankup.force.client: true

  # Permiso general del plugin - ACTUALIZADO
  survivalcore.*:
    description: Todos los permisos del plugin (incluyendo sistema híbrido)
    default: op
    children:
      survivalcore.repair: true
      survivalcore.birthday: true
      survivalcore.perfil: true
      survivalcore.score: true
      survivalcore.genero: true
      survivalcore.sellwand.*: true
      survivalcore.xptransfer.*: true
      survivalcore.cheque.*: true
      survivalcore.rankup.admin.*: true
      survivalcore.xpbank.*: true
      survivalcore.flowerpot.admin.*: true

  survivalcore.xpbank.*:
    description: Todos los permisos de XpBank
    default: op
    children:
      survivalcore.xpbank.give: true

  survivalcore.xpbank.give:
    description: Permite obtener ánforas de experiencia
    default: op

  # Permisos de macetas mágicas
  survivalcore.flowerpot.use:
    description: Permite usar comandos básicos de macetas mágicas
    default: true

  survivalcore.flowerpot.place:
    description: Permite colocar macetas mágicas
    default: true

  survivalcore.flowerpot.break:
    description: Permite romper macetas mágicas
    default: true

  survivalcore.flowerpot.interact:
    description: Permite interactuar con macetas mágicas (plantar flores)
    default: true

  # Permisos administrativos de macetas
  survivalcore.flowerpot.give:
    description: Permite dar macetas mágicas a otros jugadores
    default: op

  survivalcore.flowerpot.admin:
    description: Permisos administrativos del sistema de macetas
    default: op

  survivalcore.flowerpot.unlimited:
    description: Sin límite de macetas por jugador
    default: op

  survivalcore.flowerpot.bypass:
    description: Permite saltarse restricciones de colocación
    default: op

  # Permisos consolidados para facilitar gestión
  survivalcore.flowerpot.*:
    description: Todos los permisos básicos de macetas mágicas
    default: true
    children:
      survivalcore.flowerpot.use: true
      survivalcore.flowerpot.place: true
      survivalcore.flowerpot.break: true
      survivalcore.flowerpot.interact: true

  survivalcore.flowerpot.admin.*:
    description: Todos los permisos administrativos de macetas
    default: op
    children:
      survivalcore.flowerpot.*: true
      survivalcore.flowerpot.give: true
      survivalcore.flowerpot.admin: true
      survivalcore.flowerpot.unlimited: true
      survivalcore.flowerpot.bypass: true

  # Permisos de flores mágicas
  survivalcore.magicflower.*:
    description: Todos los permisos de flores mágicas
    default: op
    children:
      survivalcore.magicflower.give: true

  survivalcore.rankup.use:
    description: Permite intentar hacer rankup
    default: true

  survivalcore.rankup.info:
    description: Permite ver información de rangos
    default: true
  survivalcore.repair.admin:
    description: Acceso a comandos administrativos de reparación
    default: op

  survivalcore.repair.free:
    description: Reparación completamente gratuita
    default: false

  survivalcore.repair.discount.legend:
    description: 70% descuento en reparaciones
    default: false

  survivalcore.repair.discount.vip:
    description: 50% descuento en reparaciones
    default: false

  survivalcore.repair.discount.premium:
    description: 25% descuento en reparaciones
    default: false

  survivalcore.repair.discount:
    description: 15% descuento básico en reparaciones
    default: false

  survivalcore.repair.nocooldown:
    description: Sin cooldown entre reparaciones
    default: false

  survivalcore.repair.reload:
    description: Recargar configuración de reparación
    default: op

  survivalcore.repair.admin.notify:
    description: Recibir notificaciones de reparaciones grandes
    default: op