name: SurvivalCore
main: gc.grivyzom.survivalcore.Main
version: 1.0
author: Brocolitx
api-version: 1.13
commands:
  score:
    description: Comando principal para SurvivalCore.
    usage: /score <reload>
  perfil:
    description: Muestra tu perfil y te permite subir el nivel de Granjería.
    usage: /perfil
  skills:
    description: "Abre el menú de habilidades"
    usage: /skills
  genero:
    description: Selecciona tu género desde un menú gráfico.
    usage: /genero
  birthday:
    description: "Configura o anuncia tu cumpleaños"
    usage: /birthday
    aliases: [cumpleaños, cumpleanos]
  lectern:
    description: Gestión de recetas de Atril
    usage: /lectern <subcmd>
    aliases: [atril]
  xpgive:
    description: Transfiere experiencia de tu barra a otro jugador
    usage: /xpgive <jugador> <cantidad>
    aliases: [transferxp, darxp]
  xptransfers:
    description: Muestra información sobre tus transferencias diarias
    usage: /xptransfers
    aliases: [transferinfo, xlimits]
  xptransferlog:
    description: Muestra el historial de transferencias (solo staff)
    usage: /xptransferlog <jugador> [días]
    aliases: [xplog, transferlog]
  repair:
    description: Repara completamente el ítem en mano a cambio de experiencia
    usage: /repair [cost|info|help]
    aliases: [reparar, fix]
permissions:
  survivalcore.reload:
    description: Permite recargar la configuración del plugin.
    default: op
  survivalcore.xpbank.upgrade:
    description: Permite mejorar el Banco de Experiencia
    default: true
  survivalcore.use.lectern:
    description: Permite interactuar con Atriles Mágicos
    default: false
  survivalcore.transfer.rank.default:
    description: Límites de transferencia para jugadores default
    default: true
  survivalcore.transfer.rank.vip:
    description: Límites de transferencia para VIPs
    default: false
  survivalcore.transfer.rank.elite:
    description: Límites de transferencia para Elite
    default: false
  survivalcore.transfer.rank.mod:
    description: Límites de transferencia para Moderadores
    default: false
  survivalcore.transfer.rank.admin:
    description: Límites de transferencia para Administradores (ilimitado)
    default: op
  survivalcore.transferlog:
    description: Permite ver historial de transferencias de otros jugadores
    default: op