name: SurvivalCore
main: gc.grivyzom.survivalcore.Main
version: 1.0
author: Brocolitx
api-version: 1.13
commands:
  score:
    description: Comando principal para SurvivalCore.
    usage: /score <reload>
  perfil:
    description: Muestra tu perfil y te permite subir el nivel de Granjería.
    usage: /perfil
  skills:
    description: "Abre el menú de habilidades"
    usage: /skills
  genero:
    description: Selecciona tu género desde un menú gráfico.
    usage: /genero
  birthday:
    description: "Configura o anuncia tu cumpleaños"
    usage: /birthday
    aliases: [cumpleaños, cumpleanos]
  lectern:
    description: Gestión de recetas de Atril
    usage: /lectern <subcmd>
    aliases: [atril]
  xpgive:
    description: Transfiere experiencia de tu barra a otro jugador
    usage: /xpgive <jugador> <cantidad>
    aliases: [transferxp, darxp]
  xptransfers:
    description: Muestra información sobre tus transferencias diarias
    usage: /xptransfers
    aliases: [transferinfo, xlimits]
  xptransferlog:
    description: Muestra el historial de transferencias (solo staff)
    usage: /xptransferlog <jugador> [días]
    aliases: [xplog, transferlog]
  repair:
    description: Repara completamente el ítem en mano a cambio de experiencia
    usage: /repair [cost|info|help]
    aliases: [reparar, fix]
  sellwand:
    description: "Gestiona el sistema SellWand"
    usage: /sellwand <give|reload|limits|prices|info|help> [argumentos]
    aliases: [sw, varita, varitaventa]
permissions:
  survivalcore.reload:
    description: Permite recargar la configuración del plugin.
    default: op
  survivalcore.xpbank.upgrade:
    description: Permite mejorar el Banco de Experiencia
    default: true
  survivalcore.use.lectern:
    description: Permite interactuar con Atriles Mágicos
    default: false
  survivalcore.transfer.rank.default:
    description: Límites de transferencia para jugadores default
    default: true
  survivalcore.transfer.rank.vip:
    description: Límites de transferencia para VIPs
    default: false
  survivalcore.transfer.rank.elite:
    description: Límites de transferencia para Elite
    default: false
  survivalcore.transfer.rank.mod:
    description: Límites de transferencia para Moderadores
    default: false
  survivalcore.transfer.rank.admin:
    description: Límites de transferencia para Administradores (ilimitado)
    default: op
  survivalcore.transferlog:
    description: Permite ver historial de transferencias de otros jugadores
    default: op
  survivalcore.repair:
    description: Permite usar el comando /reparar básico
    default: true
  survivalcore.repair.all:
    description: Permite reparar todos los ítems del inventario
    default: true
  survivalcore.repair.armor:
    description: Permite reparar toda la armadura
    default: true
  survivalcore.repair.weapon:
    description: Permite reparar armas
    default: true
  survivalcore.repair.tool:
    description: Permite reparar herramientas
    default: true
  survivalcore.repair.nocooldown:
    description: Ignora el cooldown de reparación
    default: op
  survivalcore.repair.discount:
    description: Obtiene 25% de descuento en costos de reparación
    default: false
  survivalcore.repair.discount.vip:
    description: Obtiene 50% de descuento en costos de reparación
    default: false
  survivalcore.repair.free:
    description: Reparación completamente gratuita (admin)
    default: op
  survivalcore.sellwand.*:
    description: "Acceso completo al sistema SellWand"
    children:
      survivalcore.sellwand.use: true
      survivalcore.sellwand.give: true
      survivalcore.sellwand.reload: true
      survivalcore.sellwand.prices: true
    default: op

  survivalcore.sellwand.use:
    description: "Permite usar SellWands"
    default: true

  survivalcore.sellwand.give:
    description: "Permite dar SellWands a otros jugadores"
    default: op

  survivalcore.sellwand.reload:
    description: "Permite recargar la configuración de SellWand"
    default: op

  survivalcore.sellwand.prices:
    description: "Permite ver los precios de items"
    default: true