name: SurvivalCore
version: '${project.version}'
main: gc.grivyzom.survivalcore.Main
api-version: '1.20'
authors: [ Brocolitx ]
description: Plugin principal para el servidor de supervivencia
website: https://grivyzom.gc/

# Dependencias opcionales
softdepend: [LuckPerms, PlaceholderAPI, Vault]

commands:
  # Comandos b치sicos existentes
  repair:
    description: Repara el item que tienes en la mano
    usage: /repair
    aliases: [reparar]
  birthday:
    description: Configura tu fecha de cumplea침os
    usage: /birthday [fecha]
  perfil:
    description: Ver el perfil de un jugador
    usage: /perfil [jugador]
  score:
    description: Ver tu puntuaci칩n
    usage: /score
  genero:
    description: Configura tu g칠nero
    usage: /genero
  lectern:
    description: Comandos del atril m치gico
    usage: /lectern
  # Comandos de transferencia XP
  xpgive:
    description: Dar experiencia a un jugador
    usage: /xpgive <jugador> <cantidad>
    permission: survivalcore.xptransfer.give
  xptransfers:
    description: Ver historial de transferencias
    usage: /xptransfers
  xptransferlog:
    description: Ver log de transferencias
    usage: /xptransferlog
    permission: survivalcore.xptransfer.log
  # Comandos SellWand
  sellwand:
    description: Obtener vara de venta
    usage: /sellwand
    aliases: [sw]
    permission: survivalcore.sellwand.use
  # Comandos Cheques XP
  cheque:
    description: Crear cheques de experiencia
    usage: /cheque <cantidad>
    permission: survivalcore.cheque.create
  # ========== COMANDOS DE RANKUP ==========
  rankup:
    description: Comando principal del sistema de rankup
    usage: |
      /rankup - Intentar subir de rango
      /rankup info - Ver informaci칩n del rango actual
      /rankup progress - Ver progreso hacia el siguiente rango
      /rankup list - Ver lista de rangos
      /rankup help - Mostrar ayuda
      /rankup reload - Recargar configuraci칩n (admin)
    aliases: [rangoup, ru]
    permission-message: "춶cNo tienes permisos para usar este comando."
  prestige:
    description: Comando del sistema de prestige
    usage: |
      /prestige - Intentar hacer prestige
      /prestige info - Ver informaci칩n de prestige
      /prestige help - Mostrar ayuda
      /prestige list - Ver lista de prestiges
    aliases: [prestigio, prest]
    permission-message: "춶cNo tienes permisos para usar este comando."
  ranks:
    description: Men칰 de rangos y gesti칩n del sistema
    usage: |
      /ranks - Abrir men칰 principal de rangos
      /ranks gui - Abrir interfaz gr치fica
      /ranks list - Ver lista de rangos
      /ranks top - Ver ranking de jugadores
      /ranks history - Ver historial de rankups
    aliases: [rangos, ranking]
    permission-message: "춶cNo tienes permisos para usar este comando."
  xpbank:
    description: Obtener 치nforas de experiencia (banco de XP)
    usage: |
      /xpbank - Obtener 1 치nfora vac칤a
      /xpbank <cantidad> - Obtener cantidad espec칤fica de 치nforas vac칤as
      /xpbank <cantidad> <xp> - Obtener 치nforas con XP espec칤fica
    permission: survivalcore.xpbank.give
    aliases: [anfora, experiencepot]
  # ========== 游 COMANDOS DE MACETAS M츼GICAS ==========
  flowerpot:
    description: Gesti칩n de Macetas M치gicas y Flores M치gicas
    usage: |
      === COMANDOS DE MACETAS ===
      /flowerpot give <jugador> [nivel] [cantidad] - Dar macetas m치gicas
      /flowerpot info - Ver informaci칩n de la maceta en tu mano
      /flowerpot stats - Ver estad칤sticas del sistema (admin)
      /flowerpot reload - Recargar configuraci칩n (admin)
      
      === COMANDOS DE FLORES ===
      /flowerpot giveflower <jugador> <tipo> [nivel] [cantidad] - Dar flores m치gicas
      /flowerpot list - Ver todas las flores disponibles
      
      === AYUDA ===
      /flowerpot help - Mostrar ayuda completa
      /flowerpot restrictions - Ver restricciones del sistema
    aliases: [maceta, magicpot, mpot, magicflower]
    permission: survivalcore.flowerpot.use
    permission-message: "춶cNo tienes permisos para usar este comando."
  # ========== 游 COMANDOS DE FLORES M츼GICAS ==========
  magicflower:
    description: Gesti칩n de Flores M치gicas
    usage: |
      /magicflower give <jugador> <tipo> <cantidad> <nivel> - Dar flores m치gicas
      /magicflower list - Ver todas las flores m치gicas disponibles
      /magicflower info - Ver informaci칩n de la flor en tu mano
      /magicflower help - Mostrar ayuda
    aliases: [flor, flower, mflower]
    permission: survivalcore.magicflower.use
    permission-message: "춶cNo tienes permisos para usar este comando."
# Permisos del sistema
permissions:
  # Permisos b치sicos existentes
  survivalcore.repair:
    description: Permite usar el comando repair
    default: true

  survivalcore.birthday:
    description: Permite configurar cumplea침os
    default: true

  survivalcore.perfil:
    description: Permite ver perfiles
    default: true

  survivalcore.score:
    description: Permite ver puntuaci칩n
    default: true

  survivalcore.genero:
    description: Permite configurar g칠nero
    default: true

  # Permisos SellWand
  survivalcore.sellwand.*:
    description: Todos los permisos de SellWand
    default: op
    children:
      survivalcore.sellwand.use: true
      survivalcore.sellwand.admin: true

  survivalcore.sellwand.use:
    description: Permite usar las varas de venta
    default: true

  survivalcore.sellwand.admin:
    description: Permisos administrativos de SellWand
    default: op

  # Permisos XP Transfer
  survivalcore.xptransfer.*:
    description: Todos los permisos de transferencia XP
    default: op
    children:
      survivalcore.xptransfer.give: true
      survivalcore.xptransfer.log: true

  survivalcore.xptransfer.give:
    description: Permite dar XP a otros jugadores
    default: op

  survivalcore.xptransfer.log:
    description: Permite ver logs de transferencias
    default: op

  # Permisos Cheques XP
  survivalcore.cheque.*:
    description: Todos los permisos de cheques
    default: op
    children:
      survivalcore.cheque.create: true
      survivalcore.cheque.admin: true

  survivalcore.cheque.create:
    description: Permite crear cheques de XP
    default: true

  survivalcore.cheque.admin:
    description: Permisos administrativos de cheques
    default: op

  # ========== PERMISOS DE RANKUP ==========

  # Permisos b치sicos de rankup - Todos los jugadores pueden usar
  survivalcore.rankup:
    description: Permite usar comandos b치sicos de rankup
    default: true

  survivalcore.rankup.use:
    description: Permite intentar hacer rankup
    default: true

  survivalcore.rankup.info:
    description: Permite ver informaci칩n de rangos
    default: true

  survivalcore.rankup.progress:
    description: Permite ver progreso de rankup
    default: true

  survivalcore.rankup.list:
    description: Permite ver lista de rangos
    default: true

  survivalcore.rankup.gui:
    description: Permite abrir el men칰 de rangos
    default: true

  survivalcore.rankup.history:
    description: Permite ver historial de rankups
    default: true

  # Permisos de prestige
  survivalcore.prestige:
    description: Permite usar el sistema de prestige
    default: true

  survivalcore.prestige.use:
    description: Permite hacer prestige
    default: true

  survivalcore.prestige.info:
    description: Permite ver informaci칩n de prestige
    default: true

  # Permisos administrativos de rankup
  survivalcore.rankup.admin:
    description: Permisos administrativos del sistema de rankup
    default: op

  survivalcore.rankup.reload:
    description: Permite recargar la configuraci칩n de rankup
    default: op

  survivalcore.rankup.bypass:
    description: Permite saltarse requisitos de rankup
    default: op

  survivalcore.rankup.others:
    description: Permite hacer rankup a otros jugadores
    default: op

  # Permisos consolidados para facilitar gesti칩n
  survivalcore.rankup.*:
    description: Todos los permisos de rankup (jugadores)
    default: true
    children:
      survivalcore.rankup: true
      survivalcore.rankup.use: true
      survivalcore.rankup.info: true
      survivalcore.rankup.progress: true
      survivalcore.rankup.list: true
      survivalcore.rankup.gui: true
      survivalcore.rankup.history: true
      survivalcore.prestige: true
      survivalcore.prestige.use: true
      survivalcore.prestige.info: true

  survivalcore.rankup.admin.*:
    description: Todos los permisos administrativos de rankup
    default: op
    children:
      survivalcore.rankup.*: true
      survivalcore.rankup.admin: true
      survivalcore.rankup.reload: true
      survivalcore.rankup.bypass: true
      survivalcore.rankup.others: true

  # Permiso general del plugin
  survivalcore.*:
    description: Todos los permisos del plugin
    default: op
    children:
      survivalcore.repair: true
      survivalcore.birthday: true
      survivalcore.perfil: true
      survivalcore.score: true
      survivalcore.genero: true
      survivalcore.sellwand.*: true
      survivalcore.xptransfer.*: true
      survivalcore.cheque.*: true
      survivalcore.rankup.admin.*: true
      survivalcore.xpbank.*: true
      survivalcore.flowerpot.admin.*: true

  survivalcore.xpbank.*:
    description: Todos los permisos de XpBank
    default: op
    children:
      survivalcore.xpbank.give: true

  survivalcore.xpbank.give:
    description: Permite obtener 치nforas de experiencia
    default: op


  survivalcore.flowerpot.use:
    description: Permite usar comandos b치sicos de macetas m치gicas
    default: true

  survivalcore.flowerpot.place:
    description: Permite colocar macetas m치gicas
    default: true

  survivalcore.flowerpot.break:
    description: Permite romper macetas m치gicas
    default: true

  survivalcore.flowerpot.interact:
    description: Permite interactuar con macetas m치gicas (plantar flores)
    default: true

  # Permisos administrativos
  survivalcore.flowerpot.give:
    description: Permite dar macetas m치gicas a otros jugadores
    default: op

  survivalcore.flowerpot.admin:
    description: Permisos administrativos del sistema de macetas
    default: op

  survivalcore.flowerpot.unlimited:
    description: Sin l칤mite de macetas por jugador
    default: op

  survivalcore.flowerpot.bypass:
    description: Permite saltarse restricciones de colocaci칩n
    default: op

  # Permisos consolidados para facilitar gesti칩n
  survivalcore.flowerpot.*:
    description: Todos los permisos b치sicos de macetas m치gicas
    default: true
    children:
      survivalcore.flowerpot.use: true
      survivalcore.flowerpot.place: true
      survivalcore.flowerpot.break: true
      survivalcore.flowerpot.interact: true

  survivalcore.flowerpot.admin.*:
    description: Todos los permisos administrativos de macetas
    default: op
    children:
      survivalcore.flowerpot.*: true
      survivalcore.flowerpot.give: true
      survivalcore.flowerpot.admin: true
      survivalcore.flowerpot.unlimited: true
      survivalcore.flowerpot.bypass: true
  survivalcore.magicflower.*:
    description: Todos los permisos de flores m치gicas
    default: op
    children:
      survivalcore.magicflower.give: true

  survivalcore.magicflower.give:
    description: Permite dar flores m치gicas a otros jugadores
    default: op